"use strict"

export interface Instruction {
  name: string
  summary: string
}

export const INSTRUCTIONS: Instruction[] = [
  { name: "mov", summary: "Copies the source operand to the destination. `mov dest, src`" },
  { name: "movzx", summary: "Moves a smaller value into a larger register, filling with zeros." },
  { name: "movsx", summary: "Moves a smaller value into a larger register, preserving the sign." },
  { name: "xchg", summary: "Exchanges the contents of two operands." },
  { name: "cmove", summary: "Copies the source to the destination only if equal (ZF = 1)." },
  { name: "cmovne", summary: "Copies the source to the destination only if not equal (ZF = 0)." },
  { name: "cmovg", summary: "Copies the source to the destination only if greater (signed)." },
  { name: "cmovl", summary: "Copies the source to the destination only if less (signed)." },
  { name: "cmova", summary: "Copies the source to the destination only if above (unsigned)." },
  { name: "cmovb", summary: "Copies the source to the destination only if below (unsigned)." },
  { name: "lea", summary: "Loads the effective address of the source into the destination." },
  { name: "push", summary: "Pushes a value onto the stack." },
  { name: "pop", summary: "Pops the top value off the stack into the operand." },
  { name: "pushad", summary: "Pushes all 32-bit general purpose registers onto the stack." },
  { name: "popad", summary: "Pops all 32-bit general purpose registers off the stack." },
  { name: "pushfd", summary: "Pushes the 32-bit EFLAGS register onto the stack." },
  { name: "popfd", summary: "Pops the top of the stack into the 32-bit EFLAGS register." },
  { name: "add", summary: "Adds the source to the destination. `add dest, src`" },
  { name: "sub", summary: "Subtracts the source from the destination. `sub dest, src`" },
  { name: "adc", summary: "Adds the source plus the carry flag to the destination." },
  { name: "sbb", summary: "Subtracts the source and the carry flag from the destination." },
  { name: "inc", summary: "Increments the operand by one." },
  { name: "dec", summary: "Decrements the operand by one." },
  { name: "mul", summary: "Unsigned multiply of EAX by the operand (result in EDX:EAX)." },
  { name: "imul", summary: "Signed multiply." },
  { name: "div", summary: "Unsigned divide of EDX:EAX by the operand (quotient in EAX, remainder in EDX)." },
  { name: "idiv", summary: "Signed divide of EDX:EAX by the operand." },
  { name: "daa", summary: "Adjusts AL after adding two packed BCD values." },
  { name: "das", summary: "Adjusts AL after subtracting two packed BCD values." },
  { name: "aaa", summary: "Adjusts AL after adding two unpacked BCD values." },
  { name: "aas", summary: "Adjusts AL after subtracting two unpacked BCD values." },
  { name: "aam", summary: "Adjusts AX after multiplying two unpacked BCD values." },
  { name: "aad", summary: "Adjusts AX before dividing two unpacked BCD values." },
  { name: "neg", summary: "Replaces the operand with its two's complement (negates it)." },
  { name: "cmp", summary: "Compares two operands by subtracting and setting flags. `cmp a, b`" },
  { name: "and", summary: "Bitwise AND of the two operands." },
  { name: "or", summary: "Bitwise OR of the two operands." },
  { name: "xor", summary: "Bitwise exclusive OR. `xor eax, eax` zeroes a register." },
  { name: "not", summary: "Bitwise NOT (inverts every bit)." },
  { name: "test", summary: "Bitwise AND that sets flags without storing the result." },
  { name: "bt", summary: "Copies the selected bit of the operand into the carry flag." },
  { name: "bts", summary: "Copies the selected bit into the carry flag, then sets it." },
  { name: "btr", summary: "Copies the selected bit into the carry flag, then clears it." },
  { name: "btc", summary: "Copies the selected bit into the carry flag, then inverts it." },
  { name: "bsf", summary: "Scans from bit 0 for the first set bit and stores its index." },
  { name: "bsr", summary: "Scans from the highest bit for the first set bit and stores its index." },
  { name: "shl", summary: "Shifts bits left, filling with zeros (multiplies by 2 each shift)." },
  { name: "shr", summary: "Shifts bits right, filling with zeros (unsigned divide by 2)." },
  { name: "sal", summary: "Arithmetic shift left (same as shl)." },
  { name: "sar", summary: "Arithmetic shift right, preserving the sign bit." },
  { name: "shld", summary: "Shifts the destination left, filling from the high bits of the source." },
  { name: "shrd", summary: "Shifts the destination right, filling from the low bits of the source." },
  { name: "rol", summary: "Rotates bits left." },
  { name: "ror", summary: "Rotates bits right." },
  { name: "rcl", summary: "Rotates bits left through the carry flag." },
  { name: "rcr", summary: "Rotates bits right through the carry flag." },
  { name: "jmp", summary: "Unconditional jump to a label." },
  { name: "je", summary: "Jump if equal (ZF = 1). Same as jz." },
  { name: "jne", summary: "Jump if not equal (ZF = 0). Same as jnz." },
  { name: "jz", summary: "Jump if zero (ZF = 1)." },
  { name: "jnz", summary: "Jump if not zero (ZF = 0)." },
  { name: "jg", summary: "Jump if greater (signed)." },
  { name: "jge", summary: "Jump if greater or equal (signed)." },
  { name: "jl", summary: "Jump if less (signed)." },
  { name: "jle", summary: "Jump if less or equal (signed)." },
  { name: "ja", summary: "Jump if above (unsigned)." },
  { name: "jae", summary: "Jump if above or equal (unsigned)." },
  { name: "jb", summary: "Jump if below (unsigned)." },
  { name: "jbe", summary: "Jump if below or equal (unsigned)." },
  { name: "jc", summary: "Jump if carry flag set." },
  { name: "jnc", summary: "Jump if carry flag clear." },
  { name: "jo", summary: "Jump if overflow flag set." },
  { name: "js", summary: "Jump if sign flag set (result negative)." },
  { name: "jns", summary: "Jump if sign flag clear (result not negative)." },
  { name: "jno", summary: "Jump if overflow flag clear." },
  { name: "jp", summary: "Jump if parity flag set (even number of one bits). Same as jpe." },
  { name: "jnp", summary: "Jump if parity flag clear. Same as jpo." },
  { name: "loop", summary: "Decrements ECX and jumps to the label while ECX is not zero." },
  { name: "loope", summary: "Decrements ECX and jumps while ECX is not zero and ZF = 1." },
  { name: "loopne", summary: "Decrements ECX and jumps while ECX is not zero and ZF = 0." },
  { name: "loopz", summary: "Same as loope." },
  { name: "loopnz", summary: "Same as loopne." },
  { name: "jecxz", summary: "Jump if ECX is zero (does not change ECX)." },
  { name: "call", summary: "Calls a procedure, pushing the return address." },
  { name: "ret", summary: "Returns from a procedure." },
  { name: "cdq", summary: "Sign-extends EAX into EDX:EAX (used before idiv)." },
  { name: "cbw", summary: "Sign-extends AL into AX." },
  { name: "cwd", summary: "Sign-extends AX into DX:AX." },
  { name: "cwde", summary: "Sign-extends AX into EAX." },
  { name: "nop", summary: "No operation." },
  { name: "int", summary: "Software interrupt." },
  { name: "clc", summary: "Clears the carry flag." },
  { name: "stc", summary: "Sets the carry flag." },
  { name: "cmc", summary: "Complements (inverts) the carry flag." },
  { name: "cld", summary: "Clears the direction flag, so string operations move forward." },
  { name: "std", summary: "Sets the direction flag, so string operations move backward." },
  { name: "cli", summary: "Clears the interrupt flag (disables maskable interrupts)." },
  { name: "sti", summary: "Sets the interrupt flag (enables maskable interrupts)." },
  { name: "sete", summary: "Sets the byte operand to 1 if equal (ZF = 1), otherwise 0." },
  { name: "setne", summary: "Sets the byte operand to 1 if not equal (ZF = 0), otherwise 0." },
  { name: "setg", summary: "Sets the byte operand to 1 if greater (signed), otherwise 0." },
  { name: "setge", summary: "Sets the byte operand to 1 if greater or equal (signed)." },
  { name: "setl", summary: "Sets the byte operand to 1 if less (signed), otherwise 0." },
  { name: "setle", summary: "Sets the byte operand to 1 if less or equal (signed)." },
  { name: "seta", summary: "Sets the byte operand to 1 if above (unsigned), otherwise 0." },
  { name: "setb", summary: "Sets the byte operand to 1 if below (unsigned), otherwise 0." },
  { name: "movsb", summary: "Copies a byte from [ESI] to [EDI] and advances both." },
  { name: "movsw", summary: "Copies a word from [ESI] to [EDI] and advances both." },
  { name: "movsd", summary: "Copies a doubleword from [ESI] to [EDI] and advances both." },
  { name: "stosb", summary: "Stores AL at [EDI] and advances EDI." },
  { name: "stosw", summary: "Stores AX at [EDI] and advances EDI." },
  { name: "stosd", summary: "Stores EAX at [EDI] and advances EDI." },
  { name: "lodsb", summary: "Loads the byte at [ESI] into AL and advances ESI." },
  { name: "lodsw", summary: "Loads the word at [ESI] into AX and advances ESI." },
  { name: "lodsd", summary: "Loads the doubleword at [ESI] into EAX and advances ESI." },
  { name: "scasb", summary: "Compares AL with the byte at [EDI] and advances EDI." },
  { name: "scasw", summary: "Compares AX with the word at [EDI] and advances EDI." },
  { name: "scasd", summary: "Compares EAX with the doubleword at [EDI] and advances EDI." },
  { name: "cmpsb", summary: "Compares the bytes at [ESI] and [EDI] and advances both." },
  { name: "cmpsw", summary: "Compares the words at [ESI] and [EDI] and advances both." },
  { name: "cmpsd", summary: "Compares the doublewords at [ESI] and [EDI] and advances both." },
  { name: "rep", summary: "Repeats the following string instruction ECX times." },
  { name: "repe", summary: "Repeats the following string instruction while equal and ECX is not zero." },
  { name: "repne", summary: "Repeats the following string instruction while not equal and ECX is not zero." },
  { name: "repz", summary: "Same as repe." },
  { name: "repnz", summary: "Same as repne." },
]

export const MNEMONICS: Set<string> = new Set(INSTRUCTIONS.map((i) => i.name.toLowerCase()))
