"use strict"

export interface Irvine32Proc {
  name: string
  summary: string
  receives: string
  returns: string
}

export const IRVINE32_PROCS: Irvine32Proc[] = [
  {
    name: "CloseFile",
    summary: "Closes a file that was opened for reading or writing.",
    receives: "EAX = file handle.",
    returns: "EAX is nonzero when the file was closed successfully.",
  },
  {
    name: "Clrscr",
    summary: "Clears the console window and locates the cursor at the top left.",
    receives: "Nothing.",
    returns: "Nothing.",
  },
  {
    name: "CreateOutputFile",
    summary: "Creates a new file for writing, replacing any existing file with the same name.",
    receives: "EDX = offset of a null-terminated file name.",
    returns: "EAX = a file handle, or INVALID_HANDLE_VALUE (-1) if the file could not be created.",
  },
  {
    name: "Crlf",
    summary: "Writes an end-of-line sequence to the console (moves to a new line).",
    receives: "Nothing.",
    returns: "Nothing.",
  },
  {
    name: "Delay",
    summary: "Pauses the program for a given number of milliseconds.",
    receives: "EAX = number of milliseconds.",
    returns: "Nothing.",
  },
  {
    name: "DumpMem",
    summary: "Writes a range of memory to the console in hexadecimal.",
    receives: "ESI = start address, ECX = number of units, EBX = unit size in bytes.",
    returns: "Nothing.",
  },
  {
    name: "DumpRegs",
    summary: "Displays the EAX, EBX, ECX, EDX, ESI, EDI, EBP, ESP registers and flags.",
    receives: "Nothing.",
    returns: "Nothing.",
  },
  {
    name: "GetCommandTail",
    summary: "Copies the command line arguments into a buffer.",
    receives: "EDX = offset of a 129-byte buffer.",
    returns: "CF set if the command line was empty, otherwise the buffer holds the arguments.",
  },
  {
    name: "GetDateTime",
    summary: "Gets the current system date and time.",
    receives: "EDX = offset of a 64-bit SYSTEMTIME structure.",
    returns: "The structure is filled in.",
  },
  {
    name: "GetMaxXY",
    summary: "Returns the size of the console window buffer.",
    receives: "Nothing.",
    returns: "DL = number of columns, DH = number of rows.",
  },
  {
    name: "GetMseconds",
    summary: "Returns the number of milliseconds elapsed since midnight.",
    receives: "Nothing.",
    returns: "EAX = the elapsed milliseconds, useful for timing a section of code.",
  },
  {
    name: "GetTextColor",
    summary: "Returns the current console foreground and background colors.",
    receives: "Nothing.",
    returns: "AH = background color, AL = foreground color.",
  },
  {
    name: "Gotoxy",
    summary: "Moves the cursor to a given row and column in the console window.",
    receives: "DH = row (Y), DL = column (X).",
    returns: "Nothing.",
  },
  {
    name: "IsDigit",
    summary: "Checks whether a character is a decimal digit.",
    receives: "AL = the character to test.",
    returns: "ZF set if AL holds a digit between 0 and 9.",
  },
  {
    name: "MsgBox",
    summary: "Displays a popup message box.",
    receives: "EDX = offset of the message, EBX = offset of the title (or 0).",
    returns: "Nothing.",
  },
  {
    name: "MsgBoxAsk",
    summary: "Displays a popup message box with Yes and No buttons.",
    receives: "EDX = offset of the question, EBX = offset of the title (or 0).",
    returns: "EAX = IDYES (6) or IDNO (7).",
  },
  {
    name: "OpenInputFile",
    summary: "Opens an existing file for reading.",
    receives: "EDX = offset of a null-terminated file name.",
    returns: "EAX = a file handle, or INVALID_HANDLE_VALUE (-1) if the file could not be opened.",
  },
  {
    name: "ParseDecimal32",
    summary: "Converts an unsigned decimal string into a 32-bit integer.",
    receives: "EDX = offset of the string, ECX = string length.",
    returns: "EAX = the integer value, or zero with CF set if the string was invalid.",
  },
  {
    name: "ParseInteger32",
    summary: "Converts a string of digits into a 32-bit signed integer.",
    receives: "EDX = offset of the string, ECX = string length.",
    returns: "EAX = the integer value.",
  },
  {
    name: "Random32",
    summary: "Generates a 32-bit pseudo-random integer.",
    receives: "Nothing.",
    returns: "EAX = random integer in the range 0 to FFFFFFFFh.",
  },
  {
    name: "Randomize",
    summary: "Seeds the random number generator from the system time.",
    receives: "Nothing.",
    returns: "Nothing.",
  },
  {
    name: "RandomRange",
    summary: "Generates a pseudo-random integer within a range.",
    receives: "EAX = upper bound (exclusive).",
    returns: "EAX = random integer in the range 0 to (N - 1).",
  },
  {
    name: "ReadChar",
    summary: "Waits for a single character to be typed and returns it.",
    receives: "Nothing.",
    returns: "AL = the character (not echoed to the screen).",
  },
  {
    name: "ReadDec",
    summary: "Reads an unsigned 32-bit decimal integer from the keyboard.",
    receives: "Nothing.",
    returns: "EAX = the value entered.",
  },
  {
    name: "ReadFromFile",
    summary: "Reads a block of bytes from an open file into a buffer.",
    receives: "EAX = file handle, EDX = offset of the buffer, ECX = size of the buffer.",
    returns: "EAX = the number of bytes read, or CF set with EAX = the error code.",
  },
  {
    name: "ReadHex",
    summary: "Reads a 32-bit hexadecimal integer from the keyboard.",
    receives: "Nothing.",
    returns: "EAX = the value entered.",
  },
  {
    name: "ReadInt",
    summary: "Reads a signed 32-bit integer from the keyboard.",
    receives: "Nothing.",
    returns: "EAX = the value entered (CF set on overflow).",
  },
  {
    name: "ReadKey",
    summary: "Checks for a waiting keystroke without blocking the program.",
    receives: "Nothing.",
    returns: "ZF set if no key was pressed; otherwise AL = the ASCII code and AH = the scan code.",
  },
  {
    name: "ReadString",
    summary: "Reads a line of text from the keyboard into a buffer.",
    receives: "EDX = offset of the buffer, ECX = max characters to read + 1.",
    returns: "EAX = count of characters read.",
  },
  {
    name: "SetTextColor",
    summary: "Sets the foreground and background color for console text.",
    receives: "EAX = (background * 16) + foreground.",
    returns: "Nothing.",
  },
  {
    name: "ShowFPUStack",
    summary: "Writes the floating point unit's register stack to the console.",
    receives: "Nothing.",
    returns: "Nothing.",
  },
  {
    name: "Str_compare",
    summary: "Compares two null-terminated strings and sets the flags.",
    receives: "ESI = offset of the first string, EDI = offset of the second string.",
    returns: "The Zero and Carry flags, as if the strings had been compared with cmp.",
  },
  {
    name: "Str_copy",
    summary: "Copies a null-terminated string into a destination buffer.",
    receives: "ESI = offset of the source, EDI = offset of the destination.",
    returns: "Nothing. The destination must be large enough to hold the source.",
  },
  {
    name: "Str_length",
    summary: "Returns the length of a null-terminated string.",
    receives: "EDX = offset of the string.",
    returns: "EAX = the length in bytes.",
  },
  {
    name: "Str_trim",
    summary: "Removes trailing occurrences of a character from a string.",
    receives: "EDX = offset of the string, AL = the character to remove.",
    returns: "Nothing. The string is trimmed in place.",
  },
  {
    name: "Str_ucase",
    summary: "Converts a null-terminated string to upper case.",
    receives: "EDX = offset of the string.",
    returns: "Nothing. The string is converted in place.",
  },
  {
    name: "StrLength",
    summary: "Returns the length of a null-terminated string.",
    receives: "EDX = offset of the string.",
    returns: "EAX = the length in bytes.",
  },
  {
    name: "WaitMsg",
    summary: 'Displays "Press any key..." and waits for a key press.',
    receives: "Nothing.",
    returns: "Nothing.",
  },
  {
    name: "WriteBin",
    summary: "Writes an integer to the console in binary (ASCII).",
    receives: "EAX = the value to write.",
    returns: "Nothing.",
  },
  {
    name: "WriteBinB",
    summary: "Writes an integer to the console in binary, using a chosen size.",
    receives: "EAX = the value to write, EBX = size in bytes (1, 2, or 4).",
    returns: "Nothing.",
  },
  {
    name: "WriteChar",
    summary: "Writes a single character to the console.",
    receives: "AL = the character.",
    returns: "Nothing.",
  },
  {
    name: "WriteDec",
    summary: "Writes an unsigned 32-bit integer to the console in decimal.",
    receives: "EAX = the value to write.",
    returns: "Nothing.",
  },
  {
    name: "WriteHex",
    summary: "Writes a 32-bit integer to the console in hexadecimal.",
    receives: "EAX = the value to write.",
    returns: "Nothing.",
  },
  {
    name: "WriteHexB",
    summary: "Writes an integer to the console in hexadecimal, using a chosen size.",
    receives: "EAX = the value to write, EBX = size in bytes (1, 2, or 4).",
    returns: "Nothing.",
  },
  {
    name: "WriteInt",
    summary: "Writes a signed 32-bit integer to the console in decimal.",
    receives: "EAX = the value to write.",
    returns: "Nothing.",
  },
  {
    name: "WriteStackFrame",
    summary: "Writes the current procedure's stack frame to the console.",
    receives: "EAX = number of passed arguments, EBX = number of local doublewords, ECX = number of saved registers.",
    returns: "Nothing.",
  },
  {
    name: "WriteStackFrameName",
    summary: "Writes the current stack frame, labelled with the procedure name.",
    receives: "The same values as WriteStackFrame, plus EDX = offset of the procedure name.",
    returns: "Nothing.",
  },
  {
    name: "WriteString",
    summary: "Writes a null-terminated string to the console.",
    receives: "EDX = offset of the string.",
    returns: "Nothing.",
  },
  {
    name: "WriteToFile",
    summary: "Writes a buffer to an open file.",
    receives: "EAX = file handle, EDX = offset of the buffer, ECX = number of bytes to write.",
    returns: "EAX = the number of bytes written, or zero if the write failed.",
  },
  {
    name: "WriteWindowsMsg",
    summary: "Writes the most recent Windows error message to the console.",
    receives: "Nothing.",
    returns: "Nothing. Useful after a file operation fails.",
  },
]
